"""Thin project orchestration for exploratory data analysis."""

from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd
from portfolio_management.analytics import (
    calculate_returns,
    correlation_matrix,
    dataset_overview,
    descriptive_statistics,
    detect_outliers,
    missing_value_summary,
    rolling_compounded_return,
    rolling_correlation,
    rolling_volatility,
)
from portfolio_management.risk import drawdown_series
from portfolio_management.visualization import (
    BaseFigure,
    CorrelationHeatmapFigure,
    DistributionFigure,
    DrawdownFigure,
    MissingDataFigure,
    OutlierFigure,
    PriceFigure,
    ReturnFigure,
    RollingCorrelationFigure,
    RollingVolatilityFigure,
)

from portfolio_management_project.config import ResearchConfig
from portfolio_management_project.exceptions import DataPipelineError
from portfolio_management_project.inputs import read_prices

LOGGER = logging.getLogger(__name__)


@dataclass(frozen=True)
class EDAResult:
    """Contain EDA tables, figures, interpretations, and export paths."""

    prices: pd.DataFrame
    returns: pd.DataFrame
    overview: pd.DataFrame
    missing_values: pd.DataFrame
    return_statistics: pd.DataFrame
    correlations: pd.DataFrame
    outliers: pd.DataFrame
    outlier_summary: pd.DataFrame
    rolling_volatility: pd.DataFrame
    rolling_returns: pd.DataFrame
    rolling_correlation: pd.Series
    drawdowns: pd.DataFrame
    drawdown_summary: pd.DataFrame
    interpretations: tuple[str, ...]
    figures: dict[str, BaseFigure]


@dataclass(frozen=True)
class EDAExportResult:
    """Contain directories and report path generated by the EDA export."""

    tables_directory: Path
    figures_directory: Path
    summary_path: Path


def run_eda_pipeline(
    config: ResearchConfig,
    *,
    prices: pd.DataFrame | None = None,
    export: bool = True,
) -> tuple[EDAResult, EDAExportResult | None]:
    """Load the governed universe, call library EDA APIs, and export artifacts."""
    source = read_prices(config) if prices is None else prices.copy()
    missing_assets = [ticker for ticker in config.universe.tickers if ticker not in source]
    if missing_assets:
        raise DataPipelineError(f"Processed prices omit investable assets: {missing_assets}.")
    investable_prices = source.loc[:, config.universe.tickers].sort_index()
    calculated = calculate_returns(investable_prices, method="simple", dropna=False)
    assert isinstance(calculated, pd.DataFrame)
    returns = calculated.dropna(how="all")

    overview = dataset_overview(investable_prices)
    missing = missing_value_summary(investable_prices)
    statistics = descriptive_statistics(returns)
    correlations = correlation_matrix(returns)
    outliers = detect_outliers(
        returns,
        method=config.eda.outlier_method,  # type: ignore[arg-type]
        threshold=config.eda.outlier_threshold,
    )
    outlier_summary = pd.DataFrame(
        {
            "outlier_observations": outliers.sum().astype(int),
            "outlier_fraction": outliers.mean(),
        }
    )
    volatility = rolling_volatility(
        returns,
        window=config.eda.rolling_volatility_window,
        periods_per_year=config.eda.periods_per_year,
    )
    rolling_returns = rolling_compounded_return(
        returns,
        window=config.eda.rolling_return_window,
    )
    asset_a, asset_b = config.eda.rolling_correlation_assets
    rolling_pair = rolling_correlation(
        returns,
        asset_a,
        asset_b,
        window=config.eda.rolling_correlation_window,
    )
    underwater = drawdown_series(returns)
    assert isinstance(volatility, pd.DataFrame)
    assert isinstance(rolling_returns, pd.DataFrame)
    assert isinstance(underwater, pd.DataFrame)
    drawdown_summary = pd.DataFrame(
        {
            "maximum_drawdown": -underwater.min(),
            "trough_date": underwater.idxmin(),
        }
    )

    interpretations = _build_interpretations(
        missing=missing,
        statistics=statistics,
        correlations=correlations,
        outlier_summary=outlier_summary,
        drawdown_summary=drawdown_summary,
        periods_per_year=config.eda.periods_per_year,
    )
    figures: dict[str, BaseFigure] = {
        "normalized_prices": PriceFigure(investable_prices, normalize=True),
        "periodic_returns": ReturnFigure(returns),
        "return_distributions": DistributionFigure(returns, layout="facet"),
        "missing_data": MissingDataFigure(investable_prices),
        "return_outliers": OutlierFigure(returns, outliers),
        "correlations": CorrelationHeatmapFigure(correlations),
        "rolling_volatility": RollingVolatilityFigure(volatility),
        "rolling_correlation": RollingCorrelationFigure(rolling_pair),
        "drawdowns": DrawdownFigure(underwater),
    }
    result = EDAResult(
        prices=investable_prices,
        returns=returns,
        overview=overview,
        missing_values=missing,
        return_statistics=statistics,
        correlations=correlations,
        outliers=outliers,
        outlier_summary=outlier_summary,
        rolling_volatility=volatility,
        rolling_returns=rolling_returns,
        rolling_correlation=rolling_pair,
        drawdowns=underwater,
        drawdown_summary=drawdown_summary,
        interpretations=interpretations,
        figures=figures,
    )
    exported = export_eda_result(config, result) if export else None
    return result, exported


def export_eda_result(config: ResearchConfig, result: EDAResult) -> EDAExportResult:
    """Export EDA tables, interactive figures, and financial interpretations."""
    root = config.paths.artifacts / "eda"
    tables = root / "tables"
    figures = root / "figures"
    tables.mkdir(parents=True, exist_ok=True)
    figures.mkdir(parents=True, exist_ok=True)

    table_map = {
        "dataset_overview": result.overview,
        "missing_values": result.missing_values,
        "return_statistics": result.return_statistics,
        "correlations": result.correlations,
        "outlier_summary": result.outlier_summary,
        "rolling_volatility": result.rolling_volatility,
        "rolling_returns": result.rolling_returns,
        "rolling_correlation": result.rolling_correlation.to_frame(),
        "drawdown_summary": result.drawdown_summary,
        "drawdowns": result.drawdowns,
    }
    for name, table in table_map.items():
        table.to_csv(tables / f"{name}.csv", date_format="%Y-%m-%d")
    for name, figure in result.figures.items():
        figure.save_html(figures / f"{name}.html")

    summary_path = root / "eda_summary.md"
    lines = ["# Exploratory Data Analysis — Financial Interpretation", ""]
    lines.extend(f"- {interpretation}" for interpretation in result.interpretations)
    lines.extend(
        [
            "",
            "The findings are descriptive and sample-dependent. They are not forecasts or",
            "standalone investment recommendations.",
        ]
    )
    summary_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    LOGGER.info("EDA artifacts exported to %s.", root)
    return EDAExportResult(tables, figures, summary_path)


def _build_interpretations(
    *,
    missing: pd.DataFrame,
    statistics: pd.DataFrame,
    correlations: pd.DataFrame,
    outlier_summary: pd.DataFrame,
    drawdown_summary: pd.DataFrame,
    periods_per_year: int,
) -> tuple[str, ...]:
    missing_total = int(missing["missing_observations"].sum())
    annualized_volatility = statistics["std"] * np.sqrt(periods_per_year)
    highest_volatility = str(annualized_volatility.idxmax())
    upper_triangle = correlations.where(
        np.triu(np.ones(correlations.shape), k=1).astype(bool)
    ).stack()
    pair = upper_triangle.abs().idxmax()
    pair_correlation = float(correlations.loc[pair[0], pair[1]])
    worst_drawdown_asset = str(drawdown_summary["maximum_drawdown"].idxmax())
    worst_drawdown = float(drawdown_summary.loc[worst_drawdown_asset, "maximum_drawdown"])
    outlier_asset = str(outlier_summary["outlier_observations"].idxmax())
    outlier_count = int(outlier_summary.loc[outlier_asset, "outlier_observations"])
    return (
        f"The investable price matrix contains {missing_total:,} missing observations.",
        f"{highest_volatility} has the highest full-sample annualized volatility.",
        f"The strongest absolute pairwise correlation is {pair[0]} / {pair[1]} "
        f"at {pair_correlation:.2f}.",
        f"{worst_drawdown_asset} has the deepest full-sample drawdown at {worst_drawdown:.1%}.",
        f"{outlier_asset} has the largest number of flagged return outliers "
        f"({outlier_count:,}) under the configured rule.",
    )
